import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css"; // <== add this line
import styles from "@/styles/Home.module.css";
import Game from "./Game";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>tic-tac-toe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://repos-2024.s3.eu-north-1.amazonaws.com/tic-tac-toe-favicon"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
         {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script
          src="https://kit.fontawesome.com/0b958b4a05.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <main><Game/></main>
    </>
  );
}
